require("prototypes.entity.__init__")

require("prototypes.item.item-accumulators")
require("prototypes.item.item-solar-panels")
require("prototypes.item.item-substations")
require("prototypes.item.item-power-poles")
require("prototypes.item.item-generators")
require("prototypes.item.heat-exchanger")
require("prototypes.item.heat-pipe")
require("prototypes.item.nuclear-reactor")
require("prototypes.item.steam-turbine")

require("prototypes.recipe.recipe-accumulators")
require("prototypes.recipe.recipe-solar-panels")
require("prototypes.recipe.recipe-substations")
require("prototypes.recipe.recipe-power-poles")
require("prototypes.recipe.recipe-generators")
require("prototypes.recipe.heat-exchanger")
require("prototypes.recipe.heat-pipe")
require("prototypes.recipe.nuclear-reactor")
require("prototypes.recipe.steam-turbine")

require("prototypes.technology.technology-electrical-engineer")
